spring:
  application:
    name: discovery
  datasource:
    url: jdbc:postgresql://localhost:5432/discovery
    username: discovery
    password: discovery
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
server:
  port: 8082

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
    register-with-eureka: false
    fetch-registry: false